Refactor database
BlickLabs/Bricksa pull request #38
Opened 2017-03-15 19:36 UTC by MauricioDinki

2017-03-15 22:30 UTC, Enrique199413 approved these changes

2017-03-15 23:23 UTC, jresendiz27 approved these changes

2017-03-16 02:29 UTC, AlanSanchezP requested changes

2017-03-16 02:29 UTC, AlanSanchezP commented on .env-sample
> +export DJANGO_DEBUG="True"
Line 4 is the same as line 2

2017-03-16 19:27 UTC, AlanSanchezP approved these changes

2017-03-16 19:29 UTC, merged